# Generated by Django 5.1.3 on 2024-11-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_customer_options_customer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
